function out = inv_mix_column(inp)
for j=1:4
    out(1,j)=bi2de(bitxor(bitxor((bitxor(aes_mul(inp(1,j),14),aes_mul(inp(2,j),11))) ...
        ,aes_mul(inp(3,j),13)),aes_mul(inp(4,j),9)));
    out(2,j)=bi2de(bitxor(bitxor((bitxor(aes_mul(inp(1,j),9),aes_mul(inp(2,j),14))), ...
        aes_mul(inp(3,j),11)),aes_mul(inp(4,j),13)));
    out(3,j)=bi2de(bitxor(bitxor((bitxor(aes_mul(inp(1,j),13),aes_mul(inp(2,j),9))), ...
        aes_mul(inp(3,j),14)),aes_mul(inp(4,j),11)));
    out(4,j)=bi2de(bitxor(bitxor((bitxor(aes_mul(inp(1,j),11),aes_mul(inp(2,j),13))), ...
        aes_mul(inp(3,j),9)),aes_mul(inp(4,j),14)));
end
